options:
  username:
    description: Username to use for ceph mons - defaults to prometheus-ceph-exporter.
    type: string
    default: "prometheus-ceph-exporter"
  daemon_arguments:
    description: Daemon arguments to pass to the exporter.
    type: string
    default: ""
