{
 "title": "Ceph - Pools",
 "description": "Ceph Pools dashboard.",
 "tags": [
  "ceph",
  "pools"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cloud",
    "label": "Cloud: ",
    "query": {
     "query": "label_values(ceph_pool_objects_total, cloud)"
    }
   },
   {
    "name": "job",
    "label": "Exporter",
    "query": {
     "query": "label_values(ceph_pool_objects_total{cloud=~\"$cloud\"}, job)"
    }
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": {
     "query": "label_values(ceph_pool_objects_total{job=\"$job\",cloud=~\"$cloud\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pool: $pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_available_bytes{pool=~\"$pool\", job=\"$job\", cloud=\"$cloud\"}",
     "legendFormat": "Avilable - {{ pool }}"
    },
    {
     "expr": "ceph_pool_used_bytes{pool=~\"$pool\", job=\"$job\", cloud=\"$cloud\"}",
     "legendFormat": "Used - {{ pool }}"
    },
    {
     "expr": "ceph_pool_used_bytes{pool=~\"$pool\", job=\"$job\", cloud=\"$cloud\"} + ceph_pool_available_bytes{pool=~\"$pool\", job=\"$job\", cloud=\"$cloud\"}",
     "legendFormat": "Total - {{ pool }}"
    },
    {
     "expr": "ceph_pool_raw_used_bytes{pool=~\"$pool\", job=\"$job\", cloud=\"$cloud\"}",
     "legendFormat": "Raw - {{ pool }}"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": " ceph_pool_used_bytes{pool=\"$pool\", job=\"$job\", cloud=\"$cloud\"} / (ceph_pool_available_bytes{pool=\"$pool\", job=\"$job\", cloud=\"$cloud\"} + ceph_pool_used_bytes{pool=\"$pool\", job=\"$job\", cloud=\"$cloud\"})"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Objects in Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_objects_total{pool=~\"$pool\", cloud=\"$cloud\"}",
     "legendFormat": "Objects - {{ pool }}"
    },
    {
     "expr": "ceph_pool_dirty_objects_total{pool=~\"$pool\", cloud=\"$cloud\"}",
     "legendFormat": "Dirty Objects - {{ pool }}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "IOPS" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_pool_read_total{pool=~\"$pool\", cloud=\"$cloud\"}[3m])",
     "legendFormat": "Read - {{ pool }}"
    },
    {
     "expr": "irate(ceph_pool_write_total{pool=~\"$pool\", cloud=\"$cloud\"}[3m])",
     "legendFormat": "Write - {{ pool }}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_pool_read_bytes_total{pool=\"$pool\", cloud=\"$cloud\"}[3m])",
     "legendFormat": "Read Bytes - {{ pool }}"
    },
    {
     "expr": "irate(ceph_pool_write_bytes_total{pool=\"$pool\", cloud=\"$cloud\"}[3m])",
     "legendFormat": "Written Bytes - {{ pool }}"
    }
   ]
  }
 ]
}